# Generated by Django 5.1.3 on 2024-11-21 11:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='register',
            name='picture',
            field=models.ImageField(blank=True, upload_to='website/pics'),
        ),
    ]
