# Generated by Django 5.1.3 on 2024-11-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_arts_places_delete_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
