# Generated by Django 5.1.3 on 2024-11-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_arts_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arts',
            old_name='id',
            new_name='art_id',
        ),
    ]
