# Generated by Django 5.1.3 on 2024-11-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_id_arts_art_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='art_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
